name: Run Tests

on:
  push:
    branches:
      - main # or your default branch
      - ci-test
  pull_request:
    - main # or your default branch
    - ci-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest app/test_api.py --disable-warnings
