name: Run Tests

on:
  push:
    branches:
      - main
      - ci-test
  pull_request:
    branches:
      - main
      - ci-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: anomaly-detector-api # Set working directory for this step
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Consider adding pytest to requirements.txt

      - name: Run tests
        working-directory: anomaly-detector-api # Set working directory for this step
        env:
          API_KEY:
            ${{ secrets.API_KEY }} # <--- CHANGE THIS LINE!
            # Ensure your GitHub Secret is also named 'API_KEY'
            # (not WORKFLOW_API_KEY)
        run: |
          # PYTHONPATH is not strictly necessary if running pytest from the project root
          # and referencing app/test_api.py, but it can help with imports.
          # The path 'app/test_api.py' is relative to the working-directory.
          PYTHONPATH=. pytest app/test_api.py --disable-warnings
