name: Run Tests

on:
  push:
    branches:
      - main
      - ci-test
  pull_request:
    branches:
      - main
      - ci-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd anomaly-detector-api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd anomaly-detector-api
          pytest app/test_api.py --disable-warnings
